name: neemee-frontend-ci
description: CI validation for all branches
repositoryEventConfig:
  repositoryType: GITHUB
  repository: projects/paulbonneville-com/locations/us-central1/connections/paul-bonneville-labs-connection/repositories/Paul-Bonneville-Labs-neemee
  push:
    branch: .*
filename: frontend/cloudbuild-ci.yaml